#!/usr/bin/env bash
#
# install.sh — deploy Online Boutique v0.10.5 to the current kind cluster.
#
# This script fetches the upstream release-bundle manifest and applies it
# unmodified. For bit-exact runs, run `pin-images.sh` afterwards to resolve
# image digests, then re-apply from the pinned manifest before measured runs.
#
set -euo pipefail

OB_VERSION="v0.10.5"
NAMESPACE="${ONLINE_BOUTIQUE_NAMESPACE:-default}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MANIFEST_URL="https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/${OB_VERSION}/release/kubernetes-manifests.yaml"
LOCAL_MANIFEST="$SCRIPT_DIR/kubernetes-manifests-${OB_VERSION}.yaml"
PINNED_MANIFEST="$SCRIPT_DIR/pinned-manifest.yaml"

# Sanity: are we connected to a cluster?
if ! kubectl cluster-info >/dev/null 2>&1; then
  echo "❌  kubectl can't reach a cluster. Run 'bash infra/kind/up.sh local' first."
  exit 1
fi

# Prefer the pinned manifest if it exists (bit-exact mode).
if [[ -f "$PINNED_MANIFEST" ]]; then
  echo "▶  Using pinned manifest: $PINNED_MANIFEST"
  MANIFEST_TO_APPLY="$PINNED_MANIFEST"
else
  # Fetch upstream if we don't already have it cached.
  if [[ ! -f "$LOCAL_MANIFEST" ]]; then
    echo "▶  Fetching Online Boutique $OB_VERSION manifest…"
    curl -fsSL -o "$LOCAL_MANIFEST" "$MANIFEST_URL"
  else
    echo "✓  Using cached manifest: $LOCAL_MANIFEST"
  fi
  MANIFEST_TO_APPLY="$LOCAL_MANIFEST"
fi

# Ensure namespace exists.
kubectl get ns "$NAMESPACE" >/dev/null 2>&1 || kubectl create ns "$NAMESPACE"

# Expose the frontend on NodePort 30080 (matches kind-*.yaml extraPortMappings).
# We do this by patching the frontend-external Service after the manifest is applied.
echo "▶  Applying manifest to namespace '$NAMESPACE'…"
kubectl apply -n "$NAMESPACE" -f "$MANIFEST_TO_APPLY"

echo "▶  Patching frontend-external to NodePort 30080…"
kubectl -n "$NAMESPACE" patch svc frontend-external --type=merge -p '{
  "spec": {
    "type": "NodePort",
    "ports": [{"port": 80, "targetPort": 8080, "nodePort": 30080}]
  }
}' || true

# Apply platform-compatibility patches (see infra/online-boutique/patches/).
# These exist solely for arm64 dev hosts (DEV-007: the .NET CLR working set
# exceeds the upstream cartservice memory limit on Apple Silicon). On x86_64 —
# including the cloud measurement environment (§3.10-A) — the upstream manifest
# is deployed unmodified so measured runs carry no platform deviations.
# Patch files are strategic-merge-patch fragments (partial Deployment specs) and
# MUST be applied via 'kubectl patch --type=strategic', not 'kubectl apply -f'.
NODE_ARCH=$(kubectl get nodes -o jsonpath='{.items[0].status.nodeInfo.architecture}' 2>/dev/null || echo unknown)
if [[ "$NODE_ARCH" == "arm64" ]]; then
  echo "▶  arm64 nodes detected — applying platform patches (DEV-007)…"
  for patch in "$SCRIPT_DIR/patches/"*.yaml; do
    [[ -f "$patch" ]] || continue
    echo "   applying: $(basename "$patch")"
    kind=$(grep '^kind:' "$patch" | awk '{print tolower($2)}')
    name=$(grep '^  name:' "$patch" | head -1 | awk '{print $2}')
    kubectl -n "$NAMESPACE" patch "$kind" "$name" \
      --type=strategic \
      -p "$(cat "$patch")"
  done
else
  echo "▶  ${NODE_ARCH} nodes — skipping arm64 platform patches (upstream manifest unmodified)"
fi

# The built-in loadgenerator ships at replicas:1 and would inject
# uncontrolled background traffic into every trial. All load is generated by
# Locust under supervisor control (IMPLEMENTATION_LOG Finding 0.4 — now
# codified here instead of relying on a manual scale-down).
echo "▶  Scaling built-in loadgenerator to 0 (experiment traffic is Locust-only)…"
kubectl -n "$NAMESPACE" scale deploy/loadgenerator --replicas=0 || true

echo "▶  Waiting for all Online Boutique pods to become Ready (timeout 5 min)…"
kubectl wait --for=condition=Ready pods --all -n "$NAMESPACE" --timeout=300s 2>/dev/null || \
  kubectl -n "$NAMESPACE" get pods

echo ""
echo "✅  Online Boutique $OB_VERSION deployed."
kubectl -n "$NAMESPACE" get deploy,svc -o wide

echo ""
echo "▶  Frontend reachable at: http://localhost:30080"
echo ""
echo "Next: bash infra/online-boutique/pin-images.sh  (one-time, then re-apply for bit-exact runs)"
echo "Then: bash infra/observability/install.sh"
